### ISSUE TITLE
Send Property when Checked in by Another

### ISSUE THREAD

**Issue by dshanske** [aaronpk/OwnYourSwarm#35] opened 2017-12-09 01:25 UTC
If Swarm has who checked you in, pass that along to Micropub.

**Comment by sebsel** [comment] 2017-12-09 11:11
dub of #29 :)

**Comment by dshanske** [comment] 2017-12-23 20:39
I was sitting next to @aaronpk when I did this. I figured if someone had suggested it, he'd say so

**Comment by aaronpk** [comment] 2017-12-25 15:58
Closing as a duplicate of #29, let's continue the discussion there. Sorry I forgot about that thread in Austin!

**Closed by aaronpk** 2017-12-25 15:58 UTC
